//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureCrudExample.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_description
    {
        public int project_id { get; set; }
        public string project_name { get; set; }
        public string project_name_link { get; set; }
        public string image_link { get; set; }
        public string image_link_name { get; set; }
        public string project_location { get; set; }
        public string price_range { get; set; }
        public string Built_Up_Area { get; set; }
        public string EMI { get; set; }
        public Nullable<int> RERA { get; set; }
        public string marketed_by { get; set; }
        public string owner_name { get; set; }
        public string Owner_link { get; set; }
        public string Owner_type { get; set; }
        public string description { get; set; }
        public string nearBy_facility { get; set; }
    }
}
